name: Generate Debian Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS2 Humble
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble

    - name: Install bloom, etc
      run: sudo apt-get update && sudo apt-get install -y python3-bloom dpkg-dev debhelper

    - name: Install dependencies
      run: |
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    - name: Install nav2 dependencies
      run: sudo apt-get update && sudo apt-get install -y ros-humble-nav2-common ros-humble-nav2-core ros-humble-nav2-util ros-humble-nav2-costmap-2d ros-humble-nav2-msgs ros-humble-nav-2d-utils

    - name: Build Debian package
      run: |
        bloom-generate rosdebian --ros-distro humble
        fakeroot debian/rules binary

    - name: Verify Debian package
      run: |
        find `pwd`/../*.deb -maxdepth 1

    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: ros-humble-nav2-lyapunov-stable-controller
        path: |
	  /home/runner/work/nav2_lyapunov_stable_controller/ros-humble-nav2-lyapunov-stable-controller_0.1.0-0jammy_amd64.deb

  release:
    needs: build
    runs-on: ubuntu-22.04

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ros-humble-nav2-lyapunov-stable-controller

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: Automatically generated release from GitHub Actions
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../*.deb
        asset_name: ros-humble-nav2-lyapunov-stable-controller.deb
        asset_content_type: application/octet-stream
